apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ceicgbaua-dotnet-basic
  janus-idp.io/tekton: ceicgbaua-dotnet-basic
  backstage.io/kubernetes-id: ceicgbaua-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ceicgbaua-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
